name: Run Databricks Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Action'
        required: true
        default: 'run-pipeline'
        type: choice
        options:
          - run-pipeline
          - destroy

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  WORKSPACE_URL: "https://adb-7405615650097771.11.azuredatabricks.net"
  JOB_ID: "821578738640099"
  # Add PAT token to GitHub secrets as DATABRICKS_TOKEN

jobs:
  run-pipeline:
    name: Run Databricks Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Run Databricks Job
        run: |
          DATABRICKS_TOKEN="${{ secrets.DATABRICKS_TOKEN }}"
          
          echo "Starting Job: $JOB_ID"
          
          curl -s -X POST "${WORKSPACE_URL}/api/2.1/jobs/run-now" \
            -H "Authorization: Bearer $DATABRICKS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"job_id\": $JOB_ID}"
          
          echo "## Pipeline Started! Job ID: $JOB_ID" >> $GITHUB_STEP_SUMMARY

  destroy:
    name: Destroy Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Setup Terraform Backend
        run: |
          chmod +x scripts/setup_backend.sh
          ./scripts/setup_backend.sh
        env:
          ENVIRONMENT: dev
          PREFIX: rtsa
          LOCATION: eastus

      - name: Terraform Init
        run: cd terraform && terraform init -upgrade -backend-config=../backend_config/backend.hcl

      - name: Terraform Destroy
        run: cd terraform && terraform destroy -auto-approve -no-color
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
